const canvasActionTypes = {
  SET_CANVAS_ASPECT_RATIO: 'SET_CANVAS_ASPECT_RATIO',
  SET_CANVAS_ORIENTATION: 'SET_CANVAS_ORIENTATION',
  SET_IMAGE_ASPECT_RATIO: 'SET_IMAGE_ASPECT_RATIO',
  REORDER_CANVAS: 'REORDER_CANVAS',
};

export default canvasActionTypes;
