const layerReducer = {
  ALIGN_LAYER_HORIZONTAL: 'ALIGN_LAYER_HORIZONTAL',
  ALIGN_LAYER_VERTICAL: 'ALIGN_LAYER_VERTICAL',
  ALIGN_LAYER_CENTER: 'ALIGN_LAYER_VERTICAL',
  UPDATE_LAYER_POSITION: 'UPDATE_LAYER_POSITION',
  HIDE_LAYER: 'HIDE_LAYER',
  SHOW_LAYER: 'SHOW_LAYER',
};

export default layerReducer;
