const layerActionTypes = {
  MODIFY_LAYER_TEXT: 'MODIFY_LAYER_TEXT',
  UPDATE_LAYER_LAYOUT: 'UPDATE_LAYER_LAYOUT',
  UPDATE_BACKGROUND: 'UPDATE_BACKGROUND',
  TOGGLE_LAYER: 'TOGGLE_LAYER',
};

export default layerActionTypes;
